routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () { return view('welcome'); });
Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/myCart', 'HomeController@myCart')->name('myCart');
Route::get('/show/products', 'HomeController@products')->name('products');
Route::post('/add/carts/{product}', 'cartController@store')->name('add.carts');
Route::post('/qty/{cart}', 'cartController@update')->name('update.carts');
Route::post('delete/qty/{cart}', 'cartController@destroy')->name('delete.carts');

Route::resource('products', 'ProductController');
Route::resource('categories', 'CategoryController');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class Cart extends Pivot {
    protected $table="carts";
    protected $fillable=['qty'];
    protected $with=['product'];
    protected $attributes=[
        'qty','id'
    ];
    public function product(){ return $this->belongsTo(Product::class);}
    public function user(){ return $this->belongsTo(User::class);}

}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model{
    protected $fillable=['name'];
    public function products(){ return $this->hasMany(Product::class); }

}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model{
    protected $fillable=[ 'name', 'image', 'price', 'old_price', 'description' ];
    protected $appends=['path_image'];

    public function user(){ return $this->belongsTo(User::class); }

    public function getPathImageAttribute(){ return url('uploads/products/'.$this->image); }

    public function carts(){
        return $this->belongsToMany(User::class,'carts')->withPivot(['qty','id'])->using(Cart::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password','image','role'
    ];
//    protected $guarded=[''];

    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function products(){ return $this->hasMany(Product::class); }

    public function carts(){
        return $this->belongsToMany(User::class,'carts')->withPivot(['qty','id'])->using(Cart::class);
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Http\Requests\CreateCartRequest;
use App\Http\Requests\UpdateCartRequest;
use App\Product;
use Illuminate\Http\Request;

class CartController extends Controller{

    public function index(){

        $carts=auth()->user()->carts()->paginate();
        return view('cart.index',compact('carts'));
    }

    public function store(Product $product){
        $product->carts()->attach(auth()->id(),[ 'qty'=>1 ]);
        return back()->withSuccess('Cart Created Successfully!');
    }

    public function update(UpdateCartRequest $request, Cart $cart){
        $cart->update($request->validated());
        return back()->withSuccess('Cart Updated Successfully!');
    }

    public function destroy(Cart $cart){
        $cart->delete();
        return back()->withSuccess('Cart Deleted Successfully!');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function index(){
        $categories=Category::paginate();
        return view('category.index',compact('categories'));
    }

    public function create()
    {
        return view('category.create');
    }

    public function store(CreateCategoryRequest $request){
        $validated=$request->validated();
        Category::create($validated);
        return back()->withSuccess('Category Created Successfully!');
    }

    public function show(Category $category)
    {
        return view('category.show',compact('category'));
    }

    public function edit(Category $category)
    {
        return view('category.edit',compact('category'));
    }

    public function update(UpdateCategoryRequest $request, Category $category){
        $validated=$request->validated();
        $category->update($validated);
        return back()->withSuccess('Category Updated Successfully!');
    }

    public function destroy(Category $category){
        $category->delete();

        return back()->withSuccess('Category Deleted Successfully!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function imageUpload($folder,$input='image'){
        $request=request();
        if ($request->hasFile('image')){
            $image=$request->file('image');
            $imageName=uniqid('products-').'.'.$image->getClientOriginalExtension();
            $image->storeAs('products', $imageName);
            return $imageName;
        }
        return "image.jpg";
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class HomeController extends Controller{

    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    public function index()
    {
        return view('home');
    }

    public function myCart(){
        $carts=auth()->user()->carts()->paginate();
        return view('mycarts',compact('carts'));
    }
    public function products(){
        $products=Product::paginate();
        return view('products',compact('products'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function index(){
        $products=Product::paginate();
        return view('product.index',compact('products'));
    }

    public function create(){
        return view('product.create');
    }

    public function store(CreateProductRequest $request){
        $validated=$request->validated();
        $validated['image']=$this->imageUpload('products');
        auth()->user()->products()->create($validated);
        return back()->withSuccess('Product Created Successfully!');
    }

    public function show(Product $product)
    {
        return view('product.show',compact('product'));
    }

    public function edit(Product $product)
    {
        return view('product.edit',compact('product'));
    }

    public function update(UpdateProductRequest $request, Product $product){
        $validated=$request->validated();
        if ($request->hasFile('image')){
            $validated['image']=$this->imageUpload('products');
            unlink(public_path($product->path_image));
        }
        $product->update($validated);
        return back()->withSuccess('Product Updated Successfully!');
    }

    public function destroy(Product $product){
        $product->delete();

        return back()->withSuccess('Product Deleted Successfully!');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-title">Create</h4>
                        <form class="w-100" action="{{route('categories.store')}}"  method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">name</label>
                                <input type="text" value="{{old('name')}}" class=" @error('name') is-invalid @enderror form-control" name="name" id="name" required aria-describedby="helpIdname" placeholder="name">
                                @error('name')
                                <small id="helpIdname" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-title">Update {{$category->name}}</h4>
                        <form class="w-100" action="{{route('categories.update',$category)}}" enctype="multipart/form-data" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">name</label>
                                <input type="text" value="{{$category->name}}" class=" @error('name') is-invalid @enderror form-control" name="name" id="name" required aria-describedby="helpIdname" placeholder="name">
                                @error('name')
                                <small id="helpIdname" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-warning">Update</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-sm btn-primary" href="{{route('categories.create')}}">@lang('main.create')</a>
            </div>
            <div class="col-md-12 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{__('main.categories')}}</h4>
                        @if ($categories->count()>0)
                            <table class="table table-sm table-bordered">
                                <thead class="thead-default">
                                <tr>
                                    <th>#</th>
                                    <th>@lang('main.name')</th>
                                    <th>@lang('main.edit')</th>
                                    <th>@lang('main.delete')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($categories as $category)
                                    <tr>
                                        <td scope="row">{{++$loop->index}}</td>
                                        <td>{{$category->name}}</td>
                                        <td>
                                            <a href="{{route('categories.edit',$category)}}" class="btn btn-sm btn-warning">@lang('main.edit')</a>
                                        </td>
                                        <td>
                                            <form action="{{route('categories.destroy',$category)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger">@lang('main.delete')</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach


                                </tbody>
                            </table>
                            {{$categories->links()}}
                        @else
                            <div class="alert text-center alert-info" role="alert">
                                <strong>@lang('main.no-categories')</strong>
                            </div>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <img height="30"  class="rounded-circle" width="30" src="{{url('uploads/images/'.auth()->user()->image)}}" alt="">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @include('sweetalert::alert')

</body>
</html>

resources/views/mycarts.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if ($carts->count()>0)
                @foreach ($carts as $product)
                    <div class="col-md-12 mt-3">
                        <div class="card">
                            <div class="card-header">{{$product->name}}</div>
                            <div class="card-body">
                                <form id="cart{{$product->id}}" action="{{route('update.carts',$product->pivot->id)}}" method="post">
                                    @csrf
                                    <div class="form-group">
                                        <label for="qty">qty</label>
                                        <input onchange="this.submit()" type="number" min="1" value="{{$product->pivot->qty}}" class="form-control" name="qty" id="qty" aria-describedby="helpIdqty" placeholder="qty">
                                    </div>
                                </form>
                                <form id="cart{{$product->id}}" action="{{route('delete.carts',$product->pivot->id)}}" method="post">
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-danger">delete</button>
                                </form>

                            </div>
                        </div>
                    </div>
                @endforeach
                {{$carts->links()}}
            @else
                <div class="alert text-center alert-info w-100" role="alert">
                    <strong>no Cart</strong>
                </div>
            @endif

        </div>
    </div>
@endsection

resources/views/product/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-title">Create</h4>
                        <form class="w-100" action="{{route('products.store')}}" enctype="multipart/form-data" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">name</label>
                                <input type="text" value="{{old('name')}}" class=" @error('name') is-invalid @enderror form-control" name="name" id="name" required aria-describedby="helpIdname" placeholder="name">
                                @error('name')
                                <small id="helpIdname" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="price">price</label>
                                <input type="number" min="0" required value="{{old('price')}}" step="any" class=" @error('price') is-invalid @enderror form-control" name="price" id="price" required aria-describedby="helpIdprice" placeholder="price">
                                @error('price')
                                <small id="helpIdprice" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="old_price">old price</label>
                                <input type="number" min="0" value="{{old('old_price')}}" step="any" class=" @error('old_price') is-invalid @enderror form-control" name="old_price" id="old_price" required aria-describedby="helpIdold_price" placeholder="old_price">
                                @error('old_price')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="image">image</label>
                                <input type="file"  required class=" @error('image') is-invalid @enderror form-control" name="image" id="image" required aria-describedby="helpIdimage" placeholder="image">
                                @error('image')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="description">description</label>
                                <textarea required class=" @error('image') is-invalid @enderror form-control" name="description" id="description"  placeholder="description">{{old('description')}}</textarea>
                                @error('image')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="category_id">category</label>
                                <select class="form-control" name="category_id" id="category_id">
                                    <option>Selected Category</option>
                                    @foreach (\App\Category::all() as $category)
                                        <option  value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-title">Update {{$product->name}}</h4>
                        <form class="w-100" action="{{route('products.update',$product)}}" enctype="multipart/form-data" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">name</label>
                                <input type="text" value="{{$product->name}}" class=" @error('name') is-invalid @enderror form-control" name="name" id="name" required aria-describedby="helpIdname" placeholder="name">
                                @error('name')
                                <small id="helpIdname" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="price">price</label>
                                <input type="number" min="0" required value="{{$product->price}}" step="any" class=" @error('price') is-invalid @enderror form-control" name="price" id="price" required aria-describedby="helpIdprice" placeholder="price">
                                @error('price')
                                <small id="helpIdprice" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="old_price">old price</label>
                                <input type="number" min="0" value="{{$product->old_price}}" step="any" class=" @error('old_price') is-invalid @enderror form-control" name="old_price" id="old_price" required aria-describedby="helpIdold_price" placeholder="old_price">
                                @error('old_price')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="image">image</label>
                                <input type="file" step="any" class=" @error('image') is-invalid @enderror form-control" name="image" id="image" required aria-describedby="helpIdimage" placeholder="image">
                                <div>
                                    <img height="100" width="100" src="{{$product->path_image}}" alt="">
                                </div>
                                @error('image')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="description">description</label>
                                <textarea required class=" @error('image') is-invalid @enderror form-control" name="description" id="description"  placeholder="description">{{$product->description}}</textarea>
                                @error('image')
                                <small id="helpIdold_price" class="form-text text-muted">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="category_id">category</label>
                                <select class="form-control" name="category_id" id="category_id">
                                    <option></option>
                                    @foreach (\App\Category::all() as $category)
                                        <option {{($product->category_id && $product->category_id===$category->id)?'selected':''}} value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-warning">Update</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-sm btn-primary" href="{{route('products.create')}}">@lang('main.create')</a>
            </div>
            <div class="col-md-12 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{__('main.products')}}</h4>
                        @if ($products->count()>0)
                            <table class="table table-sm table-bordered">
                                <thead class="thead-default">
                                <tr>
                                    <th>#</th>
                                    <th>@lang('main.name')</th>
                                    <th>@lang('main.price')</th>
                                    <th>@lang('main.old_price')</th>
                                    <th>@lang('main.image')</th>
                                    <th>@lang('main.edit')</th>
                                    <th>@lang('main.delete')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($products as $product)
                                    <tr>
                                        <td scope="row">{{++$loop->index}}</td>
                                        <td>{{$product->name}}</td>
                                        <td>{{$product->price}}</td>
                                        <td>{{$product->old_price}}</td>
                                        <td><img width="100" height="50" src="{{url('uploads/products'.$product->image)}}" alt="{{$product->name}}"></td>
                                        <td>
                                            <a href="{{route('products.edit',$product)}}" class="btn btn-sm btn-warning">@lang('main.edit')</a>
                                        </td>
                                        <td>
                                            <form action="{{route('products.destroy',$product)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger">@lang('main.delete')</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach


                                </tbody>
                            </table>
                            {{$products->links()}}
                        @else
                            <div class="alert text-center alert-info" role="alert">
                                <strong>@lang('main.no-products')</strong>
                            </div>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

</div>
@endsection